
namespace CodePorting.Api.Cli;

public static class ConstLanguage
{
	public static IReadOnlyList<CodeLanguage> AllLanguages { get; } =
	[
		new ("C#", "cs"),
		new ("C++", "cpp,cxx,cc,c,c++,c++m,ccm,cppm,cxxm,hpp,hxx,hh,h,h++,inl,ipp,ixx,pcc,tcc,tpp,inc"),
		new ("Java", "java"),
		new ("Python", "py,pyw,pyi,py3,pyde,tac,wsgi,xpy"),
		new ("JavaScript", "js,mjs,cjs,njs,pac,jake,jakefile,bones,es6"),
		new ("Go", "go"),
		new ("Perl", "pl,pm,plx,ph,plh,psgi,p6,perl,al"),
		new ("R", "R,r,rd,rsx"),
		new ("Matlab", "m"),
		new ("C", "c,h,hh,ec,idc,pgc,inc"),
		new ("Julia", "jl"),
		new ("Kotlin", "kt,kts,ktm"),
		new ("PHP", "php,php3,php4,php5,phtml,ctp,phakefile,aw,inc"),
		new ("Ruby", "rb,rbw,ru,builder,jbuilder,rabl,rbx"),
		new ("Rust", "rs"),
		new ("TypeScript", "ts,tsx,mts,cts"),
		new ("Lua", "lua,wlua,nse,p8,pd_lua,rbxs"),
		new ("SAS", "sas"),
		new ("Fortran", "f,f90,f95,f03,f08,for,ftn,pfo,f77,inc,F,F90,F95,F03,F08,FOR,FTN"),
		new ("Assembler", "asm,s,S,a51,nasm"),
		new ("Lisp", "lisp,lsp,cl,el,asd"),
		new ("Scala", "scala,sbt,kojo"),
		new ("Haskell", "hs,lhs,hsc"),
		new ("ActionScript", "as"),
		new ("Clojure", "clj,cljs,cljc,cljx,boot"),
		new ("COBOL", "cob,cbl,COB,CBL,cobol,cpy,ccp"),
		new ("CoffeeScript", "coffee,cjsx,iced,Cakefile"),
		new ("Dart", "dart"),
		new ("Swift", "swift"),
		new ("Groovy", "groovy,gvy,grt,gtpl,Jenkinsfile,Gantfile"),
		new ("Elixir", "ex,exs"),
		new ("Erlang", "erl,hrl,xrl,yrl"),
		new ("Pascal", "pas,dpr,lpr,pascal"),
		new ("D", "d"),
		new ("Ada", "ada,adb,ads,pad"),
		new ("Crystal", "cr"),
		new ("Scheme", "scm,ss,sch,sld,sls,sps,sc"),
		new ("Haxe", "hx,hxsl"),
		new ("VB.NET", "vb,vbhtml"),
		new ("Objective-C", "m,mm,h"),
		new ("VBScript", "vbs,vbe,wsf"),
		new ("VB", "vb"),
		new ("VBA", "bas,cls,frm,ctl,dsr,vba"),
		new ("PowerShell", "ps1,psc1,psm1,psd1"),
		new ("Apex", "cls,tgr,page,trigger"),
		new ("OCaml", "ml,mli,mll,mly,eliom,eliomi,ml4"),
		new ("Bash", "sh,bash"),
		new ("Vala", "vala,vapi"),
		new ("Tcl", "tcl,tk,itk"),
		new ("F#", "fs,fsi,fsx"),
		new ("Racket", "rkt,rktd,rktl,scrbl"),
		new ("Elm", "elm"),
		new ("4D", "4d"),
		new ("Object Pascal", "pas,dpr,lpr,pascal,pp,inc"),
		new ("Delphi", "pas,dpr,dpk"),
		new ("Verilog", "v,sv,vh,svh"),
		new ("VHDL", "vhd,vhdl,vht,vhs"),
		new ("Chisel", "scala"),
	];
}
